name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Ensure latest version

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build  # Modify this if your build command is different

      - name: Ensure pages directory exists
        run: mkdir -p dist

      - name: Upload artifact (Fixing the issue!)
        uses: actions/upload-artifact@v4  # ✅ No deprecated v3 issues
        with:
          name: github-pages-artifact-${{ github.run_id }}
          path: dist
          retention-days: 1
          include-hidden-files: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Ensure latest version

      - name: Download artifact (Fixing the issue!)
        uses: actions/download-artifact@v4  # ✅ No deprecated v3 issues
        with:
          name: github-pages-artifact-${{ github.run_id }}
          path: dist

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4  # ✅ Ensures proper Pages setup

      - name: Upload artifact for Pages deployment
        uses: actions/upload-artifact@v4  # ✅ Fully compatible
        with:
          name: github-pages-deploy-${{ github.run_id }}
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  # ✅ Latest version
