name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build  # ⚠️ Make sure `dist` is generated

      - name: Debug: Show build output before uploading
        run: |
          echo "🛠️ Checking build output..."
          ls -R dist || echo "⚠️ ERROR: dist directory is missing or empty!"

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # ✅ MUST match deploy step
          path: dist
          retention-days: 1
          include-hidden-files: true

      - name: Debug: Confirm artifact uploaded
        run: echo "✅ Artifact uploaded!"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact for deployment
        uses: actions/download-artifact@v4
        with:
          name: github-pages  # ✅ MUST match upload step
          path: dist

      - name: Debug: Show downloaded artifact contents
        run: |
          echo "📦 Checking downloaded artifact contents..."
          ls -R dist || echo "⚠️ ERROR: dist directory is empty after download!"

      - name: Ensure dist directory exists (Fix path issues)
        run: mkdir -p dist

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # ✅ Ensure correct artifact name
